[workspace]
name = "galah"
version = "0.1.0"
description = "CoverM tool for computing various forms of DNA sequence coverage calculations"
channels = [
    "conda-forge",
    "bioconda",
]
platforms = ["linux-64"]

# Core dependencies that work across all platforms
[feature.common.dependencies]
  # These depedencies are spelled out in the README.md too, so changes need to be synced manually.
skani = ">=0.2.2"
fastani = ">=1.3"

# x86_64-specific dependencies
[feature.main.dependencies]
  # These depedencies are spelled out in the README.md too, so changes need to be synced manually.

[feature.dev.dependencies]
extern = "*"

# Define environments
[environments]
default = ["main","common"]  # Environment with x86_64-specific tools
osx = ["common"]  # Environment with common tools only
dev = ["dev","main","common"]
