[workspace]
name = "galah"
version = "0.1.0"
description = "CoverM tool for computing various forms of DNA sequence coverage calculations"
channels = [
    "conda-forge",
    "bioconda",
]
platforms = ["linux-64"]

# Core dependencies that work across all platforms
[feature.common.dependencies]
skani = ">=0.1.1"
fastani = ">=1.3"

# x86_64-specific dependencies
[feature.main.dependencies]
dashing = ">=0.4.0,<1.0"  # dashing 1.0 build gives illegal instruction errors

[feature.dev.dependencies]
extern = "*"

# Define environments
[environments]
default = ["main","common"]  # Environment with x86_64-specific tools
osx = ["common"]  # Environment with common tools only
dev = ["dev","main","common"]
